// Default game settings shared across all entry points
export const defaultGameSettings = {
  "horizontal-lines": {
    backgroundColor: "#1F1F1F",
    ballColor: "#17ACFD",
    obstacleColor: "#FF3333",
    popupText: "Discount Game",
    borderRadius: 0,
    gameAreaBorderRadius: 5,
    gameEndBorderRadius: 0,
    emailModalBorderRadius: 0,
    discountModalBorderRadius: 0,
    gameDifficulty: 50,
    maxDiscount: "35",
    mainText: "Discount Game",
    mainTextSize: "28",
    mainTextColor: "#1F1F1F",
    mainTextBgColor: "#FFFFFF",
    mainTextWeight: "600",
    secondaryText: "Discount:",
    secondaryTextColor: "#FFFFFF",
    secondaryTextSize: "24",
    secondaryTextWeight: "500",
    rulesText: "1 Score = 1% Discount",
    rulesTextColor: "#FFFFFF",
    rulesTextSize: "14",
    rulesTextWeight: "400",
    instructionText: "Move left or right",
    instructionTextColor: "#FFFFFF",
    instructionTextSize: "16",
    instructionTextWeight: "400",
    gameEndText: "Your Discount",
    gameEndTextColor: "#1F1F1F",
    gameEndTextSize: "28",
    gameEndTextWeight: "500",
    buttonText: "Try Again",
    buttonTextColor: "#FFFFFF",
    buttonTextSize: "18",
    buttonTextWeight: "500",
    claimBestButtonText: "Claim",
    claimBestButtonTextColor: "#FFFFFF",
    claimBestButtonTextSize: "18",
    claimBestButtonTextWeight: "500",
    gameEndTabBgColor: "#FFFFFF",
    buttonBgColor: "#1F1F1F",
    claimBestButtonBgColor: "#1F1F1F",
    emailModalHeadingText: "Enter Your Email",
    emailModalHeadingColor: "#1F1F1F",
    emailModalHeadingSize: "28",
    emailModalHeadingWeight: "600",
    emailModalDescriptionText: "Please enter your email address to claim your discount",
    emailModalDescriptionColor: "#1F1F1F",
    emailModalDescriptionSize: "18",
    emailModalDescriptionWeight: "400",
    emailModalSubmitText: "Submit",
    emailModalSubmitColor: "#FFFFFF",
    emailModalSubmitSize: "18",
    emailModalSubmitWeight: "500",
    emailModalCancelText: "Cancel",
    emailModalCancelColor: "#1F1F1F",
    emailModalCancelSize: "18",
    emailModalCancelWeight: "500",
    emailModalBgColor: "#FFFFFF",
    emailModalSubmitBgColor: "#1F1F1F",
    emailModalCancelBgColor: "#CCCCCC",
    discountModalHeadingText: "Your Discount Code",
    discountModalHeadingColor: "#1F1F1F",
    discountModalHeadingSize: "24",
    discountModalHeadingWeight: "600",
    discountModalDescriptionText: "Copy your code and use it at checkout!",
    discountModalDescriptionColor: "#1F1F1F",
    discountModalDescriptionSize: "16",
    discountModalDescriptionWeight: "400",
    discountModalCloseText: "Continue Shopping",
    discountModalCloseColor: "#FFFFFF",
    discountModalCloseSize: "16",
    discountModalCloseWeight: "500",
    discountModalBgColor: "#FFFFFF",
    discountModalCloseBgColor: "#1F1F1F",
  },
  "bouncing-ball": {
    backgroundColor: "#15071D",
    ballColor: "#9162F0",
    obstacleColor: "#EDD08A",
    popupText: "Discount Game",
    borderRadius: 0,
    gameAreaBorderRadius: 5,
    gameEndBorderRadius: 0,
    emailModalBorderRadius: 0,
    discountModalBorderRadius: 0,
    gameDifficulty: 50,
    maxDiscount: "35",
    mainText: "Discount Game",
    mainTextSize: "28",
    mainTextColor: "#15071D",
    mainTextBgColor: "#FFFFFF",
    mainTextWeight: "600",
    secondaryText: "Discount:",
    secondaryTextColor: "#FFFFFF",
    secondaryTextSize: "24",
    secondaryTextWeight: "500",
    rulesText: "1 Score = 1% Discount",
    rulesTextColor: "#FFFFFF",
    rulesTextSize: "14",
    rulesTextWeight: "400",
    instructionText: "Click to Bounce",
    instructionTextColor: "#FFFFFF",
    instructionTextSize: "16",
    instructionTextWeight: "400",
    gameEndText: "Your Discount",
    gameEndTextColor: "#15071D",
    gameEndTextSize: "28",
    gameEndTextWeight: "500",
    buttonText: "Try Again",
    buttonTextColor: "#FFFFFF",
    buttonTextSize: "18",
    buttonTextWeight: "500",
    claimBestButtonText: "Claim",
    claimBestButtonTextColor: "#FFFFFF",
    claimBestButtonTextSize: "18",
    claimBestButtonTextWeight: "500",
    gameEndTabBgColor: "#FFFFFF",
    buttonBgColor: "#15071D",
    claimBestButtonBgColor: "#15071D",
    emailModalHeadingText: "Enter Your Email",
    emailModalHeadingColor: "#15071D",
    emailModalHeadingSize: "28",
    emailModalHeadingWeight: "600",
    emailModalDescriptionText: "Please enter your email address to claim your discount",
    emailModalDescriptionColor: "#15071D",
    emailModalDescriptionSize: "18",
    emailModalDescriptionWeight: "400",
    emailModalSubmitText: "Submit",
    emailModalSubmitColor: "#FFFFFF",
    emailModalSubmitSize: "18",
    emailModalSubmitWeight: "500",
    emailModalCancelText: "Cancel",
    emailModalCancelColor: "#15071D",
    emailModalCancelSize: "18",
    emailModalCancelWeight: "500",
    emailModalBgColor: "#FFFFFF",
    emailModalSubmitBgColor: "#15071D",
    emailModalCancelBgColor: "#CCCCCC",
    discountModalHeadingText: "Your Discount Code",
    discountModalHeadingColor: "#15071D",
    discountModalHeadingSize: "24",
    discountModalHeadingWeight: "600",
    discountModalDescriptionText: "Copy your code and use it at checkout!",
    discountModalDescriptionColor: "#15071D",
    discountModalDescriptionSize: "16",
    discountModalDescriptionWeight: "400",
    discountModalCloseText: "Continue Shopping",
    discountModalCloseColor: "#FFFFFF",
    discountModalCloseSize: "16",
    discountModalCloseWeight: "500",
    discountModalBgColor: "#FFFFFF",
    discountModalCloseBgColor: "#15071D",
  },
  "reaction-click": {
    backgroundColor: "#021412",
    ballColor: "#00ce90",
    popupText: "Discount Game",
    borderRadius: 0,
    gameAreaBorderRadius: 5,
    gameEndBorderRadius: 0,
    emailModalBorderRadius: 0,
    discountModalBorderRadius: 0,
    gameDifficulty: 50,
    maxDiscount: "35",
    countdownTime: 10,
    mainText: "Discount Game",
    mainTextSize: "28",
    mainTextColor: "#021412",
    mainTextBgColor: "#FFFFFF",
    mainTextWeight: "600",
    secondaryText: "Discount:",
    secondaryTextColor: "#FFFFFF",
    secondaryTextSize: "24",
    secondaryTextWeight: "500",
    rulesText: "1 Score = 1% Discount",
    rulesTextColor: "#FFFFFF",
    rulesTextSize: "14",
    rulesTextWeight: "400",
    instructionText: "Click to Start",
    instructionTextColor: "#FFFFFF",
    instructionTextSize: "16",
    instructionTextWeight: "400",
    gameEndText: "Your Discount",
    gameEndTextColor: "#021412",
    gameEndTextSize: "28",
    gameEndTextWeight: "500",
    buttonText: "Try Again",
    buttonTextColor: "#FFFFFF",
    buttonTextSize: "18",
    buttonTextWeight: "500",
    claimBestButtonText: "Claim",
    claimBestButtonTextColor: "#FFFFFF",
    claimBestButtonTextSize: "18",
    claimBestButtonTextWeight: "500",
    gameEndTabBgColor: "#FFFFFF",
    buttonBgColor: "#021412",
    claimBestButtonBgColor: "#021412",
    emailModalHeadingText: "Enter Your Email",
    emailModalHeadingColor: "#021412",
    emailModalHeadingSize: "28",
    emailModalHeadingWeight: "600",
    emailModalDescriptionText: "Please enter your email address to claim your discount",
    emailModalDescriptionColor: "#021412",
    emailModalDescriptionSize: "18",
    emailModalDescriptionWeight: "400",
    emailModalSubmitText: "Submit",
    emailModalSubmitColor: "#FFFFFF",
    emailModalSubmitSize: "18",
    emailModalSubmitWeight: "500",
    emailModalCancelText: "Cancel",
    emailModalCancelColor: "#021412",
    emailModalCancelSize: "18",
    emailModalCancelWeight: "500",
    emailModalBgColor: "#FFFFFF",
    emailModalSubmitBgColor: "#021412",
    emailModalCancelBgColor: "#CCCCCC",
    discountModalHeadingText: "Your Discount Code",
    discountModalHeadingColor: "#021412",
    discountModalHeadingSize: "24",
    discountModalHeadingWeight: "600",
    discountModalDescriptionText: "Copy your code and use it at checkout!",
    discountModalDescriptionColor: "#021412",
    discountModalDescriptionSize: "16",
    discountModalDescriptionWeight: "400",
    discountModalCloseText: "Continue Shopping",
    discountModalCloseColor: "#FFFFFF",
    discountModalCloseSize: "16",
    discountModalCloseWeight: "500",
    discountModalBgColor: "#FFFFFF",
    discountModalCloseBgColor: "#021412",
  },
};

// Helper function to get complete default GameSettings data
export function getDefaultGameSettingsData(shop: string) {
  return {
    shop,
    selectedGame: "horizontal-lines",
    enabled: true,
    isActive: false,
    appEmbedEnabled: false,
    popupDelay: '3',
    popupDisplayPage: 'any',
    popupShowOnDesktop: true,
    popupShowOnMobile: true,
    emailRequired: true,
    requireName: false,
    discountCodeOrderNumber: 345,
    discountCodePrefix: "wincode",
    showStickyButton: true,
    stickyButtonText: "Discount Game",
    stickyButtonColor: "#000000",
    stickyButtonTextColor: "#ffffff",
    stickyButtonPosition: "bottom",
    stickyButtonDisplayPage: "any",
    stickyButtonShowOnDesktop: true,
    stickyButtonShowOnMobile: false,
    logoUrl: null,
    logoUrlMobile: null,
    logoScale: 100,
    logoScaleMobile: 100,
    logoHeightDesktop: "small",
    logoHeightMobile: "small",
    showPopupHeaderText: true,
    bouncingBallSettings: defaultGameSettings["bouncing-ball"],
    horizontalLinesSettings: defaultGameSettings["horizontal-lines"],
    reactionClickSettings: defaultGameSettings["reaction-click"],
  };
}
