import type { HeadersFunction, MetaFunction } from "react-router";

export const meta: MetaFunction = () => {
  return [
    { title: "Terms of Service - Discount Game" },
    { name: "description", content: "Terms of Service for Discount Game app" },
  ];
};

export const headers: HeadersFunction = () => {
  return {
    "Cache-Control": "public, max-age=3600",
  };
};

export default function Terms() {
  return (
    <div style={{ maxWidth: "800px", margin: "0 auto", padding: "2rem", fontFamily: "system-ui, -apple-system, sans-serif", lineHeight: "1.6" }}>
      <h1>Terms of Service</h1>
      <p><strong>Last updated: {new Date().toLocaleDateString()}</strong></p>

      <section style={{ marginTop: "2rem" }}>
        <h2>1. Agreement to Terms</h2>
        <p>
          By installing or using Discount Game ("the App", "we", "us", or "our"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you may not use the App.
        </p>
      </section>

      <section style={{ marginTop: "2rem" }}>
        <h2>2. Description of Service</h2>
        <p>
          Discount Game is a Shopify app that provides interactive discount games for your storefront. The App provides:
        </p>
        <ul>
          <li>Multiple interactive games (Spike Dodge, Pass the Gaps, Reaction Click)</li>
          <li>Customizable game appearance, colors, and settings</li>
          <li>Automatic discount code generation based on game performance</li>
          <li>Analytics dashboard for tracking game plays and conversions</li>
          <li>Theme integration via app blocks and app embeds</li>
          <li>Customizable popup display settings (delay, pages, mobile/desktop)</li>
        </ul>
      </section>

      <section style={{ marginTop: "2rem" }}>
        <h2>3. Eligibility</h2>
        <p>
          You must be at least 18 years old and have the legal authority to enter into these Terms. You must have an active Shopify store to use the App.
        </p>
      </section>

      <section style={{ marginTop: "2rem" }}>
        <h2>4. Subscription and Billing</h2>
        
        <h3>4.1 Subscription Plans</h3>
        <p>
          The App may be offered as a subscription service or free service. If subscription plans are available:
        </p>
        <ul>
          <li>Pricing and billing cycles will be clearly displayed during installation</li>
          <li>Free trials may be available for new users</li>
          <li>Billing is processed through Shopify's billing system</li>
        </ul>

        <h3>4.2 Free Trial</h3>
        <p>
          If a free trial is offered, you will not be charged until the trial period ends. You may cancel at any time during the trial period without being charged.
        </p>

        <h3>4.3 Billing</h3>
        <p>
          If applicable, subscription fees are charged through Shopify's billing system. Billing begins immediately after any free trial ends. Charges are processed automatically on your billing date.
        </p>

        <h3>4.4 Cancellation</h3>
        <p>
          You may cancel your subscription at any time through your Shopify admin panel. Cancellation will take effect at the end of your current billing period. You will continue to have access to the App until the end of the paid period.
        </p>

        <h3>4.5 Refunds</h3>
        <p>
          Refunds are handled according to Shopify's refund policies. We do not provide prorated refunds for partial billing periods, except as required by law.
        </p>
      </section>

      <section style={{ marginTop: "2rem" }}>
        <h2>5. User Responsibilities</h2>
        <p>You agree to:</p>
        <ul>
          <li>Provide accurate and complete information</li>
          <li>Maintain the security of your account</li>
          <li>Use the App in compliance with all applicable laws and regulations</li>
          <li>Not use the App for any illegal or unauthorized purpose</li>
          <li>Not attempt to reverse engineer, modify, or disrupt the App</li>
          <li>Ensure discount codes generated by the App comply with your local laws and Shopify's terms</li>
        </ul>
      </section>

      <section style={{ marginTop: "2rem" }}>
        <h2>6. Discount Codes</h2>
        <p>
          The App generates discount codes through Shopify's API. You are responsible for:
        </p>
        <ul>
          <li>Ensuring discount codes comply with Shopify's discount code policies</li>
          <li>Setting appropriate discount percentages and limits</li>
          <li>Managing discount code usage and expiration</li>
          <li>Complying with local laws regarding discounts and promotions</li>
        </ul>
        <p>
          We are not responsible for any issues arising from discount code usage, including but not limited to: code conflicts, invalid codes, or misuse by customers.
        </p>
      </section>

      <section style={{ marginTop: "2rem" }}>
        <h2>7. Intellectual Property</h2>
        <p>
          The App and all related content, features, and functionality are owned by us and are protected by international copyright, trademark, and other intellectual property laws. You may not copy, modify, distribute, or create derivative works based on the App.
        </p>
      </section>

      <section style={{ marginTop: "2rem" }}>
        <h2>8. Service Availability</h2>
        <p>
          We strive to maintain high availability of the App but do not guarantee uninterrupted or error-free service. The App may be temporarily unavailable due to maintenance, updates, or unforeseen circumstances. We are not liable for any downtime or service interruptions.
        </p>
      </section>

      <section style={{ marginTop: "2rem" }}>
        <h2>9. Data and Privacy</h2>
        <p>
          Your use of the App is also governed by our Privacy Policy. By using the App, you consent to the collection and use of information as described in the Privacy Policy.
        </p>
      </section>

      <section style={{ marginTop: "2rem" }}>
        <h2>10. Limitation of Liability</h2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES RESULTING FROM YOUR USE OF THE APP.
        </p>
      </section>

      <section style={{ marginTop: "2rem" }}>
        <h2>11. Indemnification</h2>
        <p>
          You agree to indemnify and hold us harmless from any claims, damages, losses, liabilities, and expenses (including legal fees) arising from your use of the App or violation of these Terms.
        </p>
      </section>

      <section style={{ marginTop: "2rem" }}>
        <h2>12. Termination</h2>
        <p>
          We reserve the right to suspend or terminate your access to the App at any time, with or without cause or notice, for any reason, including violation of these Terms. Upon termination, your right to use the App will immediately cease, and all data associated with your account will be deleted as described in our Privacy Policy.
        </p>
      </section>

      <section style={{ marginTop: "2rem" }}>
        <h2>13. Changes to Terms</h2>
        <p>
          We reserve the right to modify these Terms at any time. We will notify users of material changes by posting the updated Terms on this page with an updated "Last updated" date. Your continued use of the App after such changes constitutes acceptance of the modified Terms.
        </p>
      </section>

      <section style={{ marginTop: "2rem" }}>
        <h2>14. Governing Law</h2>
        <p>
          These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which we operate, without regard to its conflict of law provisions.
        </p>
      </section>

      <section style={{ marginTop: "2rem" }}>
        <h2>15. Contact Information</h2>
        <p>
          If you have any questions about these Terms of Service, please contact us through the Shopify Partner Dashboard or via email.
        </p>
      </section>
    </div>
  );
}
